# Generated by Django 4.1 on 2022-11-17 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_opened', models.DateField()),
                ('issue_category', models.CharField(default='', max_length=250)),
                ('transport_related', models.CharField(default='', max_length=100)),
                ('reported_issue', models.TextField(default='', max_length=1500)),
                ('reported_by_person1', models.CharField(default='', max_length=100)),
                ('reported_by_person2', models.CharField(default='', max_length=100)),
                ('issue_status', models.CharField(default='', max_length=100)),
                ('follow_up_information', models.TextField(default='', max_length=1500)),
                ('assigned_to_person1', models.CharField(default='', max_length=100)),
                ('assigned_to_person2', models.CharField(default='', max_length=100)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('date_closed', models.DateField()),
            ],
        ),
    ]
