# Generated by Django 4.1 on 2022-11-17 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communication_board', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='flight',
            table='communication_board',
        ),
    ]
