# Generated by Django 4.1 on 2022-11-17 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication_board', '0003_rename_flight_communication_board_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='communication_board',
            name='base',
            field=models.CharField(default='', max_length=250),
        ),
    ]
