# Generated by Django 4.1 on 2022-08-30 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airmedflights',
            fields=[
                ('transport_date', models.CharField(blank=True, max_length=100, null=True)),
                ('flight_num', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('base', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'airmedflights',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('transport_date', models.DateField()),
                ('flight_num', models.CharField(default='', max_length=100, primary_key=True, serialize=False, unique=True)),
                ('base', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'flight',
            },
        ),
    ]
